repos:
- repo: local
  hooks:
    - id: pytest
      name: Run pytest
      entry: bash -c "poetry run pytest tests"
      language: system
      types: [python]
      pass_filenames: false

- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
    - id: poetry-check
      args: ["-C", "."]
    - id: poetry-lock
      args: ["-C", "."]
#    - id: poetry-export
#      args: ["-C", ".", "-f", "requirements.txt", "-o", "./requirements.txt"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=20000"]
    - id: detect-private-key
    - id: check-yaml
      args:
      - --allow-multiple-documents
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        - --profile=black

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
